# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrJn2lfGRyID07nMOIkehR24o94B9NZb
"""

import pandas as pd
df = pd.read_csv('/content/Customers (1).csv', sep = ';')
df
df1 = df[(df['Age'] > 30) & (df['Income'] < 30000)]
df2 = df[(df['Profession'] == 'Lawyer') & (df['Work Experience'] > 5)]
print("Люди с возрастом больше 30 и доходом меньше 30000:")
print(df1)
print("\nЛюди с профессией 'Lawyer' и опытом работы больше 5 лет:")
print(df2)