# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13B7wXPvyAbEqhMCObvJzPGitoo9n6TWl
"""

meow = 'Death there mirth way the noisy merit'
bark = meow.split()
bark.reverse()
print(bark)

hi = 'In the hole in the ground there lived a hobbit'
for i in range(0, len(hi), 2):
    print(hi[i], end = '')

x = [3, 5, -7, -13, 43, 8, 0, -13, 8, -1, 2]
y = [z ** 2 for z in x]
print(y)

text = input()
symbol = input()
print(text.replace(symbol, symbol * 2))

text = 'xyxtentacion'
x = text.count('x')
y = text.count('y')
print('x:',x)
print('y:',y)

text = 'When he saw Sally (a girl he used to go to school with) in the shop, he could not believe his eyes. She was fantastic (as always)!'
opening_bracket = '('
closing_bracket = ')'
start_index = 0
while True:
    open_index = text.find(opening_bracket, start_index)
    if open_index == -1:
        break
    close_index = text.find(closing_bracket, open_index)
    content = (text[open_index + 1:close_index])
    print(content)
    start_index = close_index