# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6E5Np8VCswB5kNfZ_Lj7rQMmvpAOHwj
"""

a = 123
num1 = (a % 10)
num2 = ((a % 100) // 10)
num3 = (num // 100)
res = (num1 + num2 + num3)
print(res)

a = 0
for i in range(50):
    num +=i
print(num)

for n in range(7, 1000):
    if n % 7 == 0 or n % 10 == 7 or n // 10 == 7:
        print(n)