# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8713q0VBEG8wyy5GkuRBgB4hfGM1ca0
"""

import pandas as pd

ind = [chr(i) for i in range(ord('a'), ord('a') + 10)]
d = {'one': pd.Series([i + 1 for i in range(10)], index=ind),
     'two': pd.Series([i + 11 for i in range(10)], index=ind),
     'three': pd.Series([i + 21 for i in range(10)], index=ind),
     'four': pd.Series([i + 31 for i in range(10)], index=ind)}
df = pd.DataFrame(d)
print(df[:3])
print(df[-3:])

df.to_csv('output.csv', index=False)